config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django_robohash.views import robohash

urlpatterns = [
    path('', include('pylorawebchat.chat.urls')),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # robohash
    path('robohash/<string>/', robohash, name='robohash'),
    # User management
    path("users/", include("pylorawebchat.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

pylorawebchat/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [path("", views.room, name="room")]

pylorawebchat/users/urls.py
from django.urls import path

from pylorawebchat.users.views import (
    user_list_view,
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("", view=user_list_view, name="list"),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

pylorawebchat/chat/models.py
from django.db import models
from django.db.models.signals import post_save, post_delete, ModelSignal
from django.dispatch import receiver
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer


class Node(models.Model):
    address = models.CharField(max_length=4, unique=True)

    nick = models.CharField(max_length=255, blank=True)
    first_seen = models.DateTimeField(auto_now_add=True)
    last_seen = models.DateTimeField(auto_now=True)

    def __str__(self):
        return "{}: {}".format(self.address, self.nick)

    def get_all_messages(self):
        return Message.objects.filter(node=self).order_by("timestamp")

    def to_json(self, created: bool = False):

        try:
            Node.objects.get(pk=self.pk)
            delete: bool = False
        except Node.DoesNotExist:
            delete: bool = True

        return {
            "model": "node",
            "id": self.pk,
            "nick": self.nick,
            "address": self.address,
            "first_seen": self.first_seen.strftime("%Y-%m-%d %H:%M"),
            "last_seen": self.last_seen.strftime("%Y-%m-%d %H:%M"),
            "delete": delete,
            "created": created,
        }


class Message(models.Model):
    MESSAGE_TYPE = (("i", "incoming"), ("o", "outgoing"))
    node = models.ForeignKey(Node, on_delete=models.CASCADE)
    message = models.CharField(max_length=250)
    timestamp = models.DateTimeField(auto_now_add=True)
    message_type = models.CharField(max_length=1, choices=MESSAGE_TYPE)
    instant_send = models.BooleanField(default=True)

    def __str__(self):
        return "{} {} {}".format(self.message_type, self.node.nick, self.message)

    def to_json(self, created: bool = False):

        try:
            Message.objects.get(pk=self.pk)
            delete: bool = False
        except Message.DoesNotExist:
            delete: bool = True

        return {
            "model": "message",
            "id": self.pk,
            "node_id": self.node.pk,
            "node_nick": self.node.nick,
            "node_address": self.node.address,
            "message": self.message,
            "timestamp": self.timestamp.strftime("%Y-%m-%d %H:%M"),
            "message_type": self.message_type,
            "delete": delete,
            "created": created,
        }


@receiver(post_delete, sender=Message)
@receiver(post_delete, sender=Node)
@receiver(post_save, sender=Message)
@receiver(post_save, sender=Node)
def after_save_instance_handler(sender, **kwargs: ModelSignal):
    if "created" in kwargs.keys():
        created: bool = kwargs["created"]
    else:
        created: bool = False

    if isinstance(kwargs["instance"], Message):
        message: Message = kwargs["instance"]

        if message.instant_send:
            async_to_sync(get_channel_layer().group_send)(
                "chat_group",
                {"type": "chat_message", "message": message.to_json(created=created)},
            )

    if isinstance(kwargs["instance"], Node):
        node_update: Node = kwargs["instance"]

        async_to_sync(get_channel_layer().group_send)(
            "chat_group",
            {"type": "chat_message", "message": node_update.to_json(created=created)},
        )

pylorawebchat/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

pylorawebchat/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

pylorawebchat/chat/views.py
from django.http import HttpResponse
from django.shortcuts import render_to_response
from django.template import RequestContext

from .models import Node


def room(request):
    if request.user.is_superuser:
        nodes: Node = Node.objects.all().order_by("nick")

        response = render_to_response("chat/index.html", {"nodes": nodes})

    else:
        response = render_to_response("chat/403.html", {})
        response.status_code = 403

    return response

pylorawebchat/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserListView(LoginRequiredMixin, ListView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_list_view = UserListView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

pylorawebchat/chat/templates/chat/index.html
{% load static i18n compress %}<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}PyLoRaWebChat{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

  <!-- Bootstrap CSS -->
  <link id="bootswatchCSS" rel="stylesheet" crossorigin="anonymous">

  {% block css %}

    <!-- font awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" type="text/css"
          rel="stylesheet">


    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
      <!-- This file stores project-specific CSS -->

      <link href="{% static 'chat/css/style.css' %}" rel="stylesheet">

    {% endcompress %}
  {% endblock %}

  <title>PyLoRaChat</title>
</head>
<body>
<div id="connection-lost-alert" class="alert alert-dismissible alert-warning d-none">
  <h4 class="alert-heading">Connection Lost</h4>
  <p class="mb-0">try to reconnect</p>
</div>

<div>
  <div class="inbox_msg">
    <div class="inbox_people bg-light">
      <div class="headind_srch">
        <div class="recent_heading">
          <h4>Recent</h4>
        </div>
        <div class="settings_button">
          <!-- Button trigger modal -->
          <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#settingsModal">
            Settings
          </button>

          <!-- Modal -->
          <div class="modal fade" id="settingsModal" tabindex="-1" role="dialog" aria-labelledby="settingsModalLabel"
               aria-hidden="true">
            <div class="modal-dialog" role="document">
              <div class="modal-content">
                <div class="modal-header">
                  <h5 class="modal-title" id="settingsModalLabel">Settings</h5>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                <div class="modal-body">
                  <div class="btn-group" role="group" aria-label="Button group with nested dropdown">
                    <button type="button" class="btn btn-primary">set color</button>
                    <div class="btn-group" role="group">
                      <button id="btnGroupDropColor" type="button" class="btn btn-primary dropdown-toggle"
                              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"></button>
                      <div class="dropdown-menu" aria-labelledby="btnGroupDropColor">
                        <a class="dropdown-item settings-color-button" href="#" color="cerulean">Cerulean</a>
                        <a class="dropdown-item settings-color-button" href="#" color="cosmo">Cosmo</a>
                        <a class="dropdown-item settings-color-button" href="#" color="cyborg">Cyborg</a>
                        <a class="dropdown-item settings-color-button" href="#" color="darkly">Darkly</a>
                        <a class="dropdown-item settings-color-button" href="#" color="flatly">Flatly</a>
                        <a class="dropdown-item settings-color-button" href="#" color="journal">Journal</a>
                        <a class="dropdown-item settings-color-button" href="#" color="litera">Litera</a>
                        <a class="dropdown-item settings-color-button" href="#" color="lumen">Lumen</a>
                        <a class="dropdown-item settings-color-button" href="#" color="lux">Lux</a>
                        <a class="dropdown-item settings-color-button" href="#" color="materia">Materia</a>
                        <a class="dropdown-item settings-color-button" href="#" color="minty">Minty</a>
                        <a class="dropdown-item settings-color-button" href="#" color="pulse">Pulse</a>
                        <a class="dropdown-item settings-color-button" href="#" color="sandstone">Sandstone</a>
                        <a class="dropdown-item settings-color-button" href="#" color="simplex">Simplex</a>
                        <a class="dropdown-item settings-color-button" href="#" color="sketchy">Sketchy</a>
                        <a class="dropdown-item settings-color-button" href="#" color="slate">Slate</a>
                        <a class="dropdown-item settings-color-button" href="#" color="solar">Solar</a>
                        <a class="dropdown-item settings-color-button" href="#" color="spacelab">Spacelab</a>
                        <a class="dropdown-item settings-color-button" href="#" color="superhero">Superhero</a>
                        <a class="dropdown-item settings-color-button" href="#" color="united">United</a>
                        <a class="dropdown-item settings-color-button" href="#" color="yeti">Yeti</a>
                      </div>
                    </div>
                  </div>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="inbox_chat">
        {% for node in nodes %}
          <div id="chat_list_{{ node.pk }}" pk="{{ node.pk }}"
               class="chat_list {% if forloop.first %}bg-secondary{% endif %}">
            <div class="chat_people">
              <div class="chat_img"><img id="node_img_{{ node.pk }}" src="/robohash/{{ node.pk }}/?width=200&height=200"
                                         alt="{{ node.nick }}">
              </div>
              <div class="chat_ib">
                <h5 id="node_nick_{{ node.pk }}">{{ node.nick }} <span
                  class="chat_date">{{ node.last_seen|date:'Y-m-d H:i' }}</span></h5>
                <p id="node_address_{{ node.pk }}">{{ node.address }}</p>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
    </div>
    <div class="mesgs">
      {% for node in nodes %}
        <div id="msg_history_{{ node.pk }}" class="msg_history {% if not forloop.first %}d-none{% endif %}">

          {% for message in node.get_all_messages %}

            {% if message.message_type == "o" %}
              <div id="msg_{{ message.pk }}" class="outgoing_msg">
                <div id="msg_val_{{ message.pk }}" class="sent_msg alert alert-info">
                  {{ message.message }}
                  <span class="time_date"> {{ message.timestamp|date:'Y-m-d H:i' }}</span></div>
              </div>
            {% else %}
              <div id="msg_{{ message.pk }}" class="incoming_msg">
                <div class="incoming_msg_img"><img src="/robohash/{{ node.pk }}/?width=200&height=200"
                                                   alt="{{ node.nick }}">
                </div>
                <div class="received_msg">
                  <div id="msg_val_{{ message.pk }}" class="received_withd_msg alert alert-secondary">
                    {{ message.message }}
                    <span id="msg_timestamp_{{ message.pk }}"
                          class="time_date"> {{ message.timestamp|date:'Y-m-d H:i' }}</span>
                  </div>
                </div>
              </div>
            {% endif %}

          {% endfor %}

        </div>

      {% endfor %}
      <div class="type_msg">
        <div class="form-group">
          <textarea pk="{{ node.pk }}" class="form-control" rows="3" maxlength="250"></textarea>
        </div>
        <button id="send_btn" type="button" class="btn btn-primary"><i class="fa fa-paper-plane-o"
                                                                       aria-hidden="true"></i> send
        </button>
      </div>
    </div>
  </div>

</div>


{% block javascript %}

  <!-- Bootstrap JS and its dependencies-->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"
          integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
          crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
          integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
          crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
          integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
          crossorigin="anonymous"></script>

  <!-- Your stuff: Third-party javascript libraries go here -->


  <!-- place project specific Javascript in this file -->
  {% compress js %}
    <script src="{% static 'chat/js/script.js' %}"></script>
  {% endcompress %}

{% endblock javascript %}
</body>
</html>

pylorawebchat/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

pylorawebchat/templates/base.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}PyLoRaWebChat{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}
    
    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    

    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->
    
    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    
    {% endcompress %}
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'home' %}">PyLoRaWebChat</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'about' %}">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'users:detail' request.user.username  %}">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="{% url 'account_logout' %}">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="{% url 'account_signup' %}">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="{% url 'account_login' %}">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}
      
      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->
      

      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>
 

pylorawebchat/templates/pages/about.html
{% extends "base.html" %}

pylorawebchat/templates/pages/home.html
{% extends "base.html" %}

pylorawebchat/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

pylorawebchat/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn">Update</button>
      </div>
    </div>
  </form>
{% endblock %}

pylorawebchat/templates/users/user_list.html
{% extends "base.html" %}
{% load static i18n %}
{% block title %}Members{% endblock %}

{% block content %}
<div class="container">
  <h2>Users</h2>

  <div class="list-group">
    {% for user in user_list %}
      <a href="{% url 'users:detail' user.username %}" class="list-group-item">
        <h4 class="list-group-item-heading">{{ user.username }}</h4>
      </a>
    {% endfor %}
  </div>
</div>
{% endblock content %}